[package]
name = "web_1"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
tokio = {version = "1.45.0", features = ["full"]}
tower-http = { version = "0.6.3", features = ["fs"] }
